- job:
    name: storyboard-webclient-nodejs-npm4-run-test-functional
    parent: nodejs-npm-run-test
    description: |
      Run "test-functional" using nodejs.
    vars:
      npm_command: test-functional
      node_version: 4

- job:
    name: storyboard-webclient-nodejs-npm4-run-test-integration
    parent: nodejs-npm-run-test
    description: |
      Run "test-integration" using nodejs.
    vars:
      npm_command: test-integration
      node_version: 4

- job:
    name: storyboard-webclient-nodejs-npm4-run-test-unit
    parent: nodejs-npm-run-test
    description: |
      Run "test-unit" using nodejs.
    vars:
      npm_command: test-unit
      node_version: 4

- project:
    name: openstack-infra/storyboard-webclient
    check:
      jobs:
        - storyboard-webclient-nodejs-npm4-run-test-unit
        - storyboard-webclient-nodejs-npm4-run-test-functional
        - storyboard-webclient-nodejs-npm4-run-test-integration
        - build-javascript-content
    gate:
      jobs:
        - storyboard-webclient-nodejs-npm4-run-test-unit
        - storyboard-webclient-nodejs-npm4-run-test-functional
        - storyboard-webclient-nodejs-npm4-run-test-integration
        - build-javascript-content
