- job:
    name: nodejs-npm4-run-test-functional
    parent: nodejs-npm-run-test
    description: |
      Run "test-functional" using nodejs.
    vars:
      npm_command: test-functional
      node_version: 4

- job:
    name: nodejs-npm4-run-test-integration
    parent: nodejs-npm-run-test
    description: |
      Run "test-integration" using nodejs.
    vars:
      npm_command: test-integration
      node_version: 4

- job:
    name: nodejs-npm4-run-test-unit
    parent: nodejs-npm-run-test
    description: |
      Run "test-unit" using nodejs.
    vars:
      npm_command: test-unit
      node_version: 4

- job:
    name: storyboard-webclient-js-draft
    parent: nodejs-npm
    description: |
        Run "draft" using nodejs.
    post-run: playbooks/draft/post.yaml
    vars:
      npm_command: draft
      node_version: 4

- project:
    name: openstack-infra/storyboard-webclient
    check:
      jobs:
        - nodejs-npm4-run-test-unit
        - nodejs-npm4-run-test-functional
        - nodejs-npm4-run-test-integration
        - storyboard-webclient-js-draft
    gate:
      jobs:
        - nodejs-npm4-run-test-unit
        - nodejs-npm4-run-test-functional
        - nodejs-npm4-run-test-integration
        - storyboard-webclient-js-draft
