- job:
    name: nodejs-npm4-run-docs
    parent: nodejs-npm
    vars:
      npm_command: docs
      node_version: 4

- job:
    name: nodejs-npm6-run-docs
    parent: nodejs-npm
    vars:
      npm_command: docs
      node_version: 6

- job:
    name: nodejs-npm4-run-test-functional
    parent: nodejs-npm
    vars:
      npm_command: test-functional
      node_version: 4

- job:
    name: nodejs-npm4-run-test-integration
    parent: nodejs-npm
    vars:
      npm_command: test-integration
      node_version: 4

- job:
    name: nodejs-npm4-run-test-unit
    parent: nodejs-npm
    vars:
      npm_command: functional-test
      node_version: 4

- project:
    name: openstack-infra/storyboard-webclient

    check:
      jobs:
        - nodejs-npm4-run-test-unit
        - nodejs-npm4-run-test-functional
        - nodejs-npm4-run-test-integration
