- job:
    name: storyboard-webclient-nodejs-npm8-run-test-functional
    parent: nodejs-npm-run-test
    description: |
      Run "test-functional" using nodejs.
    vars:
      npm_command: test-functional
      node_version: 8

- job:
    name: storyboard-webclient-nodejs-npm8-run-test-integration
    parent: nodejs-npm-run-test
    description: |
      Run "test-integration" using nodejs.
    vars:
      npm_command: test-integration
      node_version: 8

- job:
    name: storyboard-webclient-nodejs-npm8-run-test-unit
    parent: nodejs-npm-run-test
    description: |
      Run "test-unit" using nodejs.
    vars:
      npm_command: test-unit
      node_version: 8

- project:
    check:
      jobs:
        - nodejs-npm-run-lint:
            vars:
              node_version: 8
        - storyboard-webclient-nodejs-npm8-run-test-unit
        - storyboard-webclient-nodejs-npm8-run-test-functional
        - storyboard-webclient-nodejs-npm8-run-test-integration
        - build-javascript-content:
            vars:
              javascript_content_dir: build
              npm_command: draft
              node_version: 8
    gate:
      jobs:
        - nodejs-npm-run-lint:
            vars:
              node_version: 8
        - storyboard-webclient-nodejs-npm8-run-test-unit
        - storyboard-webclient-nodejs-npm8-run-test-functional
        - storyboard-webclient-nodejs-npm8-run-test-integration
        - build-javascript-content:
            vars:
              javascript_content_dir: build
              npm_command: draft
              node_version: 8
    post:
      jobs:
        - publish-openstack-javascript-content:
            vars:
              node_version: 8
